### ISSUE TITLE
xdebug.profiler_output_dir

### ISSUE THREAD

**Issue by Niklan** [dockerizedrupal/vhost#15]
How to set `xdebug.profiler_output_dir` ?
I tried to set `- PHP_INI_XDEBUG_PROFILER_OUTPUT_DIR=/apache/data` bu no any result

**Comment by MartinAnt** [comment]
Hi,

I don't know that you are trying to accomplish but things related to xdebug should be related to PHP containers rather than vhost.

For example check the PHP 7.0 docker-compose options. You can CTRL+F "xdebug" to find options available for xdebug. So you might want to specify your environment variable for PHP container instead. Although I checked and there is no option like "PHP_INI_XDEBUG_PROFILER_OUTPUT_DIR"

https://github.com/dockerizedrupal/php-7.0-for-docker/blob/master/docker-compose.yml

**Comment by viljaste** [comment]
Closing this as this project is unfortunately not active anymore.
